# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contable', '0002_auto_20181022_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientocita',
            name='pagado',
            field=models.BooleanField(default=0),
        ),
    ]
