# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-14 04:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clinica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=45, unique=True)),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('especialidad', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('telefono', models.CharField(max_length=12)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('ultima_conexion', models.DateTimeField(auto_now_add=True)),
                ('user_type', models.CharField(choices=[('Admin', 'Admin'), ('Doctor', 'Doctor'), ('Secretaria', 'Secretaria'), ('Prueba', 'Prueba')], default='Prueba', max_length=45)),
                ('visible', models.BooleanField(default=True)),
                ('clinica', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Clinica.Clinica')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
