# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-18 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='modulo_citas',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='modulo_doctor',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='modulo_paciente',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='modulod_contable',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
