# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-30 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_usuario_clinica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Doctor', 'Doctor'), ('Secretaria', 'Secretaria')], default='Admin', max_length=45),
        ),
    ]
