# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-18 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_auto_20181118_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='modulod_contable',
            new_name='modulo_contable',
        ),
        migrations.AddField(
            model_name='usuario',
            name='modulo_secretaria',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
