# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-08 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_auto_20180929_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='clinica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Clinica.Clinica'),
        ),
    ]
