# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-18 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_auto_20181118_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='modulo_citas',
            field=models.IntegerField(choices=[('Lectura', 'Lectura'), ('Escritura', 'Escritura'), ('Eliminacion', 'Eliminacion')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='modulo_contable',
            field=models.IntegerField(choices=[('Lectura', 'Lectura'), ('Escritura', 'Escritura'), ('Eliminacion', 'Eliminacion')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='modulo_doctor',
            field=models.IntegerField(choices=[('Lectura', 'Lectura'), ('Escritura', 'Escritura'), ('Eliminacion', 'Eliminacion')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='modulo_paciente',
            field=models.IntegerField(choices=[('Lectura', 'Lectura'), ('Escritura', 'Escritura'), ('Eliminacion', 'Eliminacion')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='modulo_secretaria',
            field=models.IntegerField(choices=[('Lectura', 'Lectura'), ('Escritura', 'Escritura'), ('Eliminacion', 'Eliminacion')]),
        ),
    ]
