# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-18 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0004_auto_20181118_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='modulo_usuario',
            field=models.IntegerField(choices=[('Lectura', 'Lectura'), ('Escritura', 'Escritura'), ('Eliminacion', 'Eliminacion')], default=3),
            preserve_default=False,
        ),
    ]
