# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-19 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0006_auto_20181118_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='modulo_citas',
            field=models.IntegerField(choices=[(1, 'Lectura'), (2, 'Escritura'), (3, 'Eliminacion'), (4, 'Todos')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='modulo_contable',
            field=models.IntegerField(choices=[(1, 'Lectura'), (2, 'Escritura'), (3, 'Eliminacion'), (4, 'Todos')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='modulo_doctor',
            field=models.IntegerField(choices=[(1, 'Lectura'), (2, 'Escritura'), (3, 'Eliminacion'), (4, 'Todos')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='modulo_paciente',
            field=models.IntegerField(choices=[(1, 'Lectura'), (2, 'Escritura'), (3, 'Eliminacion'), (4, 'Todos')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='modulo_secretaria',
            field=models.IntegerField(choices=[(1, 'Lectura'), (2, 'Escritura'), (3, 'Eliminacion'), (4, 'Todos')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='modulo_usuario',
            field=models.IntegerField(choices=[(1, 'Lectura'), (2, 'Escritura'), (3, 'Eliminacion'), (4, 'Todos')]),
        ),
    ]
