# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0006_auto_20181025_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Doctor', 'Doctor'), ('Secretaria', 'Secretaria'), ('Prueba', 'Prueba')], default='Prueba', max_length=45),
        ),
    ]
