# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-22 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='moneda',
            field=models.CharField(default='Q', max_length=20),
        ),
    ]
