# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-22 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinica', '0003_auto_20181121_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinica',
            name='color_footer',
            field=models.CharField(default='#5c5c61', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='color_menu',
            field=models.CharField(default='#1f262d', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='color_texto_menu',
            field=models.CharField(default='white', max_length=50, null=True),
        ),
    ]
