# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-19 03:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paciente',
            new_name='Solicitudes',
        ),
        migrations.RenameField(
            model_name='solicitudes',
            old_name='correo_solicitante',
            new_name='correo',
        ),
    ]
