# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-08 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='direccion_clinica',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='especialidad',
            field=models.CharField(default='General', max_length=75),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='sexo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default='Masculino', max_length=20),
            preserve_default=False,
        ),
    ]
