# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-08 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_auto_20181008_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='dpi',
            field=models.CharField(default=321132123, max_length=20),
            preserve_default=False,
        ),
    ]
